# Called from main.psm1 (OnGameStarting) for every RetroArch (Steam) launch.
# $Emulator and the profile id are received as parameters instead of relying
# on ambient variables, since Playnite invokes OnGameStarting as a scriptblock
# detached from the rest of the module.
#
# The core name is read directly from the Custom profile's Arguments
# (".. -L \"cores\xxx_libretro.dll\" ..") - these are generated by
# sync-retroarch-emulators-profiles.ps1 from Playnite's own bundled RetroArch profile
# list, so the core filename is already the literal one for that profile,
# not guessed from the profile's display name (ex: "Beetle PSX HW" ->
# mednafen_psx_hw_libretro.dll).

param(
    [Parameter(Mandatory)]
    $Emulator,
    [Parameter(Mandatory)]
    [string]$EmulatorProfileId
)

$profile = $Emulator.CustomProfiles | Where-Object { $_.Id -eq $EmulatorProfileId } | Select-Object -First 1
if ($null -eq $profile) {
    Write-Warning "Emulator profile '$EmulatorProfileId' not found on '$($Emulator.Name)'."
    exit 0
}

$match = [regex]::Match($profile.Arguments, 'cores\\([^"\\]+\.dll)')
if (-not $match.Success) {
    Write-Warning "Could not extract the core name from Arguments."
    exit 0
}
$core = $match.Groups[1].Value

$coresDir = Join-Path $Emulator.InstallDir 'cores'
$corePath = Join-Path $coresDir $core

if (Test-Path $corePath) {
    exit 0
}

Write-Host "Core '$core' not found. Downloading..."

if (-not (Test-Path $coresDir)) { New-Item -ItemType Directory -Path $coresDir -Force | Out-Null }

$zipUrl  = "https://buildbot.libretro.com/nightly/windows/x86_64/latest/$core.zip"
$zipPath = Join-Path $coresDir "$core.zip"

try {
    Invoke-WebRequest -Uri $zipUrl -OutFile $zipPath -UseBasicParsing
    Expand-Archive -Path $zipPath -DestinationPath $coresDir -Force
    Remove-Item $zipPath -ErrorAction SilentlyContinue
    Write-Host "Core '$core' installed successfully."
} catch {
    Write-Error "Failed to download core '$core': $_"
    exit 1
}

exit 0
