# TODO (not implemented): syncs RetroArch saves with a self-hosted RomM
# server on game start/stop, using the "RomM Library Importer" extension
# (https://github.com/rommapp/playnite-plugin) as the credential source
# instead of asking for a RomM URL/token again - see
# Scripts\Get-RommCredentials.ps1 for what's been confirmed about that
# extension's config file so far.
#
# The emulator-matching logic below is copied as-is from
# PlayniteRetroArchSteamKit/main.psm1, where it's confirmed working on
# hardware - don't change its shape without a reason:
#   - Match by emulator Name -eq "RetroArch (Steam)", not BuiltInConfigId
#     (this is a Custom emulator, generated by
#     PlayniteRetroArchSteamKit's sync-emulator-profiles.ps1 - it has no
#     BuiltInConfigId).
#   - Playnite invokes OnGameStarting/OnGameStopped as scriptblocks detached
#     from the rest of this module - a call to a sibling function defined
#     elsewhere in this file fails at runtime with "not recognized as a
#     cmdlet", even though it's the same file. Keep all matching logic
#     inlined in each hook, don't factor it out into a helper function in
#     this module.
#   - $PlayniteApi must be passed explicitly into Scripts\*.ps1 files
#     invoked via `&` - it isn't reliably visible as an ambient variable
#     inside them.
#
# TODO: this extension only needs to run for games actually associated with
# the "RetroArch (Steam)" emulator - if PlayniteRetroArchSteamKit isn't
# installed (no such emulator exists yet), both hooks below already no-op
# via the $null check, so that's handled.

function OnGameStarting()
{
    param($evenArgs)

    $emulator = $PlayniteApi.Database.Emulators | Where-Object { $_.Name -eq "RetroArch (Steam)" } | Select-Object -First 1
    if ($null -eq $emulator)
    {
        return
    }

    $playAction = $evenArgs.Game.GameActions | Where-Object { $_.IsPlayAction -eq $true } | Select-Object -First 1
    if (($null -eq $playAction) -or
        ($playAction.Type -ne "Emulator") -or
        ($playAction.EmulatorId -ne $emulator.Id))
    {
        return
    }

    & "$PSScriptRoot\Scripts\pull-sync-save.ps1" -PlayniteApi $PlayniteApi -Emulator $emulator -EmulatorProfileId $playAction.EmulatorProfileId -Game $evenArgs.Game
}

function OnGameStopped()
{
    param($evenArgs)

    $emulator = $PlayniteApi.Database.Emulators | Where-Object { $_.Name -eq "RetroArch (Steam)" } | Select-Object -First 1
    if ($null -eq $emulator)
    {
        return
    }

    $playAction = $evenArgs.Game.GameActions | Where-Object { $_.IsPlayAction -eq $true } | Select-Object -First 1
    if (($null -eq $playAction) -or
        ($playAction.Type -ne "Emulator") -or
        ($playAction.EmulatorId -ne $emulator.Id))
    {
        return
    }

    & "$PSScriptRoot\Scripts\push-sync-save.ps1" -PlayniteApi $PlayniteApi -Emulator $emulator -EmulatorProfileId $playAction.EmulatorProfileId -Game $evenArgs.Game
}

Export-ModuleMember -Function OnGameStarting, OnGameStopped
