# Playnite script extension - manages the "RetroArch (Steam)" Custom
# emulator (profiles generated by Scripts\sync-retroarch-emulators-profiles.ps1) and
# downloads missing libretro cores on game start, so the user never has to
# run the .ps1 scripts by hand. Save-sync with RomM is out of scope here -
# it's a separate extension that depends on a RomM client extension for
# credentials, not yet developed.
#
# OnGameStarting fires for every game in the library, so it first checks
# whether the game's play action actually targets the RetroArch (Steam)
# emulator before doing anything. Playnite invokes this (and
# GetMainMenuItems-referenced functions) as scriptblocks detached from the
# rest of this module, so they can't call sibling functions defined here
# (confirmed: doing so raises "not recognized as a cmdlet" at runtime even
# though the function is right there in the same file) - all logic is
# therefore inlined in each one instead of shared through a helper.

$emulatorProfileName = "RetroArch (Steam)"

function GetMainMenuItems()
{
    param(
        $getMainMenuItemsArgs
    )

    $menuItem = New-Object Playnite.SDK.Plugins.ScriptMainMenuItem
    $menuItem.Description = "Sync $emulatorProfileName profiles"
    $menuItem.FunctionName = "Sync-RetroArchSteamProfiles"
    $menuItem.MenuSection = "@"
    return $menuItem
}

function Sync-RetroArchSteamProfiles()
{
    param(
        $actionArgs
    )

    & "$PSScriptRoot\Scripts\sync-retroarch-emulators-profiles.ps1" -PlayniteApi $PlayniteApi
}

function OnGameStarting()
{
    param(
        $evenArgs
    )

    $emulator = $PlayniteApi.Database.Emulators | Where-Object { $_.Name -eq $emulatorProfileName } | Select-Object -First 1
    if ($emulator -eq $null)
    {
        return
    }

    $playAction = $evenArgs.Game.GameActions | Where-Object { $_.IsPlayAction -eq $true } | Select-Object -First 1
    if (($playAction -eq $null) -or
        ($playAction.Type -ne "Emulator") -or
        ($playAction.EmulatorId -ne $emulator.Id))
    {
        return
    }

    & "$PSScriptRoot\Scripts\fetch-core.ps1" -Emulator $emulator -EmulatorProfileId $playAction.EmulatorProfileId
}

Export-ModuleMember -Function OnGameStarting, GetMainMenuItems, Sync-RetroArchSteamProfiles
