# Playnite script extension - hooks fetch-core/save-sync into the RetroArch
# (Steam) emulator profile (a Custom emulator named "RetroArch (Steam)",
# generated by Scripts\sync-emulator-profiles.ps1) so the user never has to
# run the .ps1 scripts by hand.
#
# OnGameStarting/OnGameStopped fire for every game in the library, so each
# handler first checks whether the game's play action actually targets the
# RetroArch (Steam) emulator before doing anything. Playnite invokes these
# functions (and GetMainMenuItems-referenced functions) as scriptblocks
# detached from the rest of this module, so they can't call sibling
# functions defined here (confirmed: doing so raises "not recognized as a
# cmdlet" at runtime even though the function is right there in the same
# file) - all logic is therefore inlined in each one instead of shared
# through a helper.

function GetMainMenuItems()
{
    param($getMainMenuItemsArgs)

    $menuItem = New-Object Playnite.SDK.Plugins.ScriptMainMenuItem
    $menuItem.Description = "Sync RetroArch (Steam) profiles"
    $menuItem.FunctionName = "Sync-RetroArchSteamProfiles"
    $menuItem.MenuSection = "@"
    return $menuItem
}

function Sync-RetroArchSteamProfiles()
{
    param($actionArgs)

    & "$PSScriptRoot\Scripts\sync-emulator-profiles.ps1" -PlayniteApi $PlayniteApi
}

function OnGameStarting()
{
    param($evenArgs)

    $emulator = $PlayniteApi.Database.Emulators | Where-Object { $_.Name -eq "RetroArch (Steam)" } | Select-Object -First 1
    if ($null -eq $emulator)
    {
        return
    }

    $playAction = $evenArgs.Game.GameActions | Where-Object { $_.IsPlayAction -eq $true } | Select-Object -First 1
    if (($null -eq $playAction) -or
        ($playAction.Type -ne "Emulator") -or
        ($playAction.EmulatorId -ne $emulator.Id))
    {
        return
    }

    & "$PSScriptRoot\Scripts\fetch-core.ps1" -Emulator $emulator -EmulatorProfileId $playAction.EmulatorProfileId
    & "$PSScriptRoot\Scripts\pull-sync-save.ps1"
}

function OnGameStopped()
{
    param($evenArgs)

    $emulator = $PlayniteApi.Database.Emulators | Where-Object { $_.Name -eq "RetroArch (Steam)" } | Select-Object -First 1
    if ($null -eq $emulator)
    {
        return
    }

    $playAction = $evenArgs.Game.GameActions | Where-Object { $_.IsPlayAction -eq $true } | Select-Object -First 1
    if (($null -eq $playAction) -or
        ($playAction.Type -ne "Emulator") -or
        ($playAction.EmulatorId -ne $emulator.Id))
    {
        return
    }

    & "$PSScriptRoot\Scripts\push-sync-save.ps1"
}

Export-ModuleMember -Function OnGameStarting, OnGameStopped, GetMainMenuItems, Sync-RetroArchSteamProfiles
