"""
Convert Playnite's official RetroArch emulator.yaml into a reference profile
list for the Steam build of RetroArch, so games launch *through* the Steam
client (steam.exe -applaunch) instead of retroarch.exe directly.

Why: the Steam build has no built-in core updater (see fetch-core.ps1), but
its folder layout (cores/, info/) and executable name are identical to the
standalone build, so profile paths don't need to change. What does need to
change is *how* the process is started: launching via Steam keeps Steam
Input, the Steam overlay, and playtime tracking working on handhelds like
the ROG Ally, where a direct retroarch.exe launch would bypass all of that.

Output goes to dist/RetroArchSteam/emulator.yaml. Playnite loads emulator
definitions by scanning <Playnite install dir>/Emulation/Emulators/*/emulator.yaml
at startup (confirmed on Playnite 10.56: dropping this folder in there makes
"RetroArch (Steam)" show up in the emulator picker) - so dist/RetroArchSteam
is meant to be copied as-is into that folder. See dist/README.md for the
end-user install steps.

NOTE: only emulator discovery is confirmed so far. Whether Playnite accepts
an Installation Folder / Executable Path split where steam.exe (used to
launch) lives outside the folder that holds the cores (used for per-profile
file detection) hasn't been verified end-to-end yet - i.e. that a profile
actually launches a game correctly. Confirm on the ROG Ally.
"""

import datetime
import sys
from pathlib import Path

import requests
import yaml

SOURCE_URL = "https://raw.githubusercontent.com/JosefNemec/Playnite/master/source/Playnite/Emulation/Emulators/RetroArch/emulator.yaml"
STEAM_APP_ID = 1118310  # RetroArch on Steam: https://store.steampowered.com/app/1118310
STEAM_EXECUTABLE_PATTERN = r"^steam\.exe$"
OUTPUT_PATH = Path(__file__).resolve().parent.parent / "dist" / "RetroArchSteam" / "emulator.yaml"

HEADER = """\
# RetroArch (Steam) - Playnite emulator definition
#
# Generated by src/convert-retroarch-to-steam-compatiblity.py from Playnite's
# official RetroArch definition: {source_url}
# Generated: {generated_at}
#
# Drop the whole "RetroArchSteam" folder (the one containing this file) into
# <your Playnite install>/Emulation/Emulators/ and restart Playnite - see
# dist/README.md for the full end-user install steps.
#
# Launching through steam.exe -applaunch keeps Steam Input, the Steam
# overlay, and playtime tracking working - a direct retroarch.exe launch
# bypasses all of that. Relative core paths (.\\cores\\...) still resolve
# correctly because Steam sets the working directory to RetroArch's install
# folder before running it, same as a normal Steam launch.
"""


def fetch_source_definition() -> dict:
    response = requests.get(SOURCE_URL, timeout=30)
    response.raise_for_status()
    return yaml.safe_load(response.text)


def to_steam_profile(profile: dict) -> dict:
    return {
        **profile,
        "StartupArguments": f"-applaunch {STEAM_APP_ID} {profile['StartupArguments']}",
        "StartupExecutable": STEAM_EXECUTABLE_PATTERN,
    }


def convert(definition: dict) -> dict:
    return {
        "Id": "retroarch_steam",
        "Name": "RetroArch (Steam)",
        "Website": f"https://store.steampowered.com/app/{STEAM_APP_ID}",
        "Profiles": [to_steam_profile(profile) for profile in definition["Profiles"]],
    }


def main() -> int:
    try:
        source_definition = fetch_source_definition()
    except requests.RequestException as error:
        print(f"Failed to fetch source emulator.yaml: {error}", file=sys.stderr)
        return 1

    steam_definition = convert(source_definition)

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    header = HEADER.format(
        source_url=SOURCE_URL,
        generated_at=datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d"),
    )
    with OUTPUT_PATH.open("w", encoding="utf-8") as output_file:
        output_file.write(header)
        output_file.write("\n")
        yaml.safe_dump(steam_definition, output_file, sort_keys=False, allow_unicode=True)

    print(f"Wrote {len(steam_definition['Profiles'])} profiles to {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
